### ISSUE TITLE
Dejo de funcionar en kodi 18.9

### ISSUE THREAD

**Issue by alvarezj81** [ramiro/service.subtitles.subdivx#49]
Antes de fin del año pasado dejó de funcionar. No encuentra nunca ningún subtitulo. Buscando en el log de kodi tira este mensaje: "SEVERE: SUBDIVX -process_page: no subtitle link regexp match found in page contents"

**Comment by ramiro** [comment]
Fixed in f640f26.

Hopefully will be able to release 0.3.8 today and it will be available from the official Kodi addons repositories soon.

Thanks @alvarezj81 for the report and thanks @pedrochiuaua for finding the issue and for the fix. Please feel free to open pull requests here.

I've lost access to computers where I can run Kodi 19.x (all my current media centers are running 18.x but I don't have too much time to watch anything) and to my Linux system where I have my dev setup. Trying to recover them so I can resume working on the addon.
